-- AlterTable
ALTER TABLE `Character` MODIFY `health` INTEGER NOT NULL DEFAULT 0,
    MODIFY `attackPower` INTEGER NOT NULL DEFAULT 0,
    MODIFY `defense` INTEGER NOT NULL DEFAULT 0,
    MODIFY `critChance` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `critMultiplier` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `evasion` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `accuracy` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `expGainRate` DOUBLE NOT NULL DEFAULT 0,
    MODIFY `goldGainRate` DOUBLE NOT NULL DEFAULT 0;
