version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lostark
      MYSQL_USER: lostark
      MYSQL_PASSWORD: FhtmxmdkRm1!
    ports:
      - "3301:3306"
      - "33061:33060"