version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RlfnrRlfnr1!
      MYSQL_DATABASE: sparta
      MYSQL_USER: sparta
      MYSQL_PASSWORD: RlfnrRlfnr1!
    ports:
      - "3301:3306"
      - "33061:33060"